apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-prod
  namespace: argocd
spec:
  project: fintech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.6.2
      helm:
        releaseName: kube-prometheus-stack-prod
        valueFiles:
          - $values/fintech-gitops/observability/monitoring/kube-prometheus-stack/values-prod.yaml
    - repoURL: https://github.com/quasar0x/fintech-platform-infra.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
