apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-dev
  namespace: argocd
spec:
  project: fintech

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-dev

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.6.2
    helm:
      releaseName: kube-prometheus-stack-dev
      valueFiles:
        - $values/fintech-gitops/observability/monitoring/kube-prometheus-stack/values-dev.yaml

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 56.6.2
      helm:
        releaseName: kube-prometheus-stack-dev
        valueFiles:
          - $values/fintech-gitops/observability/monitoring/kube-prometheus-stack/values-dev.yaml
    - repoURL: https://github.com/quasar0x/fintech-platform-infra.git
      targetRevision: develop
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
