apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-dev
  namespace: monitoring-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: grafana-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-dev-grafana
                port:
                  number: 80
