{{- if and .Values.config.enabled .Values.config.data -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fintech-service.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "fintech-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- toYaml .Values.config.data | nindent 2 }}
{{- end }}