{{- if and .Values.secrets.enabled .Values.secrets.data (not .Values.secrets.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fintech-service.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "fintech-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: |-
{{ $v | nindent 4 }}
{{- end }}
{{- end }}