{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fintech-service.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "fintech-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}