deploymentMode: SingleBinary

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi

loki:
  serviceAccount:
    create: true
    name: loki-prod
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::461508717137:role/loki-irsa-prod
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  # ✅ required
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  # ✅ IMPORTANT: snake_case key expected by chart templates
  storage_config:
    aws:
      s3: s3://us-east-1/fintech-platform-loki-prod
      region: us-east-1
      s3forcepathstyle: true

  storage:
    type: s3
    bucketNames:
      chunks: fintech-platform-loki-prod
      ruler: fintech-platform-loki-prod
      admin: fintech-platform-loki-prod
